---
- hosts: nodes
  become: true
  tasks:
  - name: Installing Apache
    yum:
      name: httpd
      state: installed
    become: yes
    tags:
      - install
  - name: startng apache
    service:
      name: httpd
      state: started
    become: yes
    tags:
      - start
