---
- hosts: nodes
  become: true
  tasks:
  - name: Installing Apache
    yum:
      name: httpd
      state: installed
    become: yes
    tags:
      - install
  - name: copying the html file
    copy:
      src: "/home/centos/index.html"
      dest: "/var/www/html"
    become: yes
    tags:
       - copy
  - name: starting Apache
    service:
      name: httpd
      state: started
    become: yes
    tags:
      - start
